# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85512b3824a8c46f1a5f4ce68256811bd28af559f47039727b4fc53e3c2135cfcfd86ec6054724bbdde2825967b64ff61d9f3f58bbb41b4216ec7d5841582ed8

test:
  secret_key_base: 69523d56b6304b1e4f80eb23dcbb97d7290bd2daabb6ae4eaa3a8f1aba94ee28634835552bdc4353ad753332aaf985ec9ef79a03eab03f95dd86e40ce9cd2e8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
